%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/lshami/School/Q12/Metagenomics/tutorial/OCD.csv
%
% Auto-generated by MATLAB on 07-May-2020 01:43:58

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Group", "Actions", "Thoughts"];
opts.VariableTypes = ["categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Group", "EmptyFieldRule", "auto");

% Import the data
OCD1 = readtable("OCD.csv", opts);


%% Clear temporary variables
clear opts

r = fitrm(OCD1, 'Actions-Thoughts ~ Group ') ;
[manovatbl,A,C,D] = manova(r)
